### ISSUE TITLE
pictures starting outside the printing area are shifted

### ISSUE THREAD

**Issue by haraldballuch** [albrechtf/mcf2pdf#5] opened 2016-02-01 14:02 UTC
If a picture area starts outside the printing area (for example when inserting a picture as a background), then the picture is shifted by mcf2pdf as if it starts exactly on the border of the printing area. This is true for picture areas with their left border left from the printing area and for pictures with their top border above the printing area at least. So probably for those with negative coordinates of their left top corner?
A possible work around is to put the border of the picture area exactly over the printing area and to zoom into the picture. This makes the same effect as if the picture would start outside the printing area.

**Comment by albrechtf** [comment] 2016-11-02 22:59
Do you also have an example here? With just moving images out of the page area, I cannot reproduce this bug (works fine). Perhaps fixed with latest version, would be great if you could test it with today's 0.3.1 release... Thanks!

**Comment by albrechtf** [comment] 2017-11-04 21:33
Closed as no response for one year.

**Closed as completed by albrechtf** 2017-11-04 21:33 UTC
